### PR TITLE
Bump go to 1.18

### PR DESCRIPTION
**Pull request by AKamyshnikova**
| Q               | A
| --------------- | ---
| Bug fix?        | []
| New feature?    | [x]
| API breaks?     | []
| Deprecations?   | []
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | Apache 2.0

### What's in this PR?
Upgrade go version to 1.18

### Why?
Keeping project with updated go version. 

- [x] Implementation tested
- [ ] Logging code meets the guideline
- [ ] User guide and development docs updated (if needed)
- [ ] Append changelog

### To Do
As followup will be update to 1.19 as Docker images already use 1.19 go base image.

### CODE REVIEW

**Review by cscetbon — APPROVED** [review]

**Comment by AKamyshnikova** [comment]
@cscetbon Hello! Do you plan to have release in near future that will include this PR?

**Comment by cscetbon** [comment]
I was going to wait for the other update you mentioned. You think it deserves its own release for some reason ?

**Comment by AKamyshnikova** [comment]
I'm afraid bumping to 1.19 won't be such easy PR as it has some breaking changes and multi-casskop has a dependency to https://github.com/admiraltyio/multicluster-controller which requires an update.

**Comment by cscetbon** [comment]
@AKamyshnikova done, see [2.1.14](https://github.com/cscetbon/casskop/releases/tag/2.1.14)

**Pull request merged**
