### PR TITLE
Fix e2e backup tests

### LINKED ISSUE #115: e2e tests failing
**What did you do?**
Currently e2e test job is failing on backup/restore test in master branch.

**What did you expect to see?**
Tests passing

**Environment**
* casskop version: master

**Possible Solution**
Increase timeout - for now its look like it is not enough time for tests to pass.

### PR DESCRIPTION
**Pull request by cscetbon**
| Q               | A
| --------------- | ---
| Bug fix?        | [X]
| New feature?    | []
| API breaks?     | []
| Deprecations?   | []
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | Apache 2.0

### What's in this PR?
Fixes #115

### CODE REVIEW

**Comment by AKamyshnikova** [comment]
@cscetbon Could you rebase this changes?

**Comment by cscetbon** [comment]
@AKamyshnikova please review

**Comment by cscetbon** [comment]
@AKamyshnikova can you review when you get a chance ?

**Review by AKamyshnikova — APPROVED** [review]

**Comment by AKamyshnikova** [comment]
@cscetbon Thank you! Sorry for delay, I was on vacation :)

**Pull request merged**
